use git instead of zip
to overcome .git/HEADS error

diff --git a/build-popcorn b/build-popcorn
--- a/build-popcorn
+++ b/build-popcorn
@@ -9,7 +9,7 @@ installdir="/opt"
 nodeversion="0.9.2"
 version="master"
 OfficialURL="http://popcorntime.io"
-gitURL="https://git.popcorntime.io/stash/plugins/servlet/archive/projects/PT/repos/popcorn-app?at=refs/heads"
+gitURL="https://git.popcorntime.io/stash/scm/pt/popcorn-app.git"
 issueURL="https://git.popcorntime.io/jira"
 icon="http://i.imgur.com/BhQu7He.png"
 log="$HOME/popcorn-build.log"
@@ -96,12 +96,12 @@ func_clean -all
 func_dependencies() {
 #package dep
 [[ -n `egrep -v '^#|^ *$' /etc/apt/sources.list /etc/apt/sources.list.d/* | grep chris-lea/node.js` ]] && nodeppa=1 || nodeppa=0
-if [ -n "`dpkg-query -W -f='${Status}\n' nodejs wget unzip | grep not`" ] || [ $nodeppa == "0" ] ; then
+if [ -n "`dpkg-query -W -f='${Status}\n' nodejs wget unzip git | grep not`" ] || [ $nodeppa == "0" ] ; then
 	echo "- Checking for dependencies 'nodejs', 'wget' and 'unzip'..."
 	sudo apt-add-repository -y ppa:chris-lea/node.js &> $log && 
 	sudo apt-get update &> $log
 
-	sudo apt-get install nodejs wget unzip -y &> $log && echo -e "  ...Ok !" || error=1
+	sudo apt-get install nodejs wget git unzip -y &> $log && echo -e "  ...Ok !" || error=1
 	func_error
 fi
 
@@ -125,15 +125,13 @@ func_build() {
 #get sources
 echo "- Downloading sources (branch:$version) from GitHub..."
 cd
-mkdir -p popcorn-app
-cd popcorn-app
-[ -e popcorn-app.zip ] && rm popcorn-app.zip
-wget $gitURL/$version -O popcorn-app.zip &> $log && unzip -o popcorn-app.zip &> $log && rm popcorn-app.zip && echo -e "  ...Ok !\n" || error=1
+[ -e popcorn-app ] && rm -rf popcorn-app
+git clone $gitURL &> $log && cd popcorn-app && echo -e "  ...Ok !\n" || error=1
 func_error
 
 #npm
 echo "- Running 'npm install'..."
-sudo chown -Rf $USER:$USER $HOME/popcorn-app/ $HOME/tmp $HOME/.npm
+sudo chown -Rf $HOME/tmp $HOME/.npm
 npm install --yes &> $log && echo -e "  ...Ok !\n" || error=1
 func_error
 
